# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  SONAR_TOKEN: $(SONAR_TOKEN)
  MAVEN_OPTS: "-Dmaven.repo.local=$(Pipeline.Workspace)/.m2/repository"

stages:
- stage: BuildAndAnalyze
  jobs:
  - job: MavenBuild
    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitecture: 'x64'
        jdkSourceOption: 'PreInstalled'

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        mavenOptions: '-Xmx1024m'

    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarQube Cloud'
        organization: '321114110002'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'java-app'
        cliProjectName: 'JAVA CI CD'
        extraProperties: |
          sonar.java.binaries=target

    - task: SonarCloudAnalyze@1

    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'

    - task: CopyFiles@2
      inputs:
        contents: '**/target/*.jar'
        targetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: DeployAndScan
  dependsOn: BuildAndAnalyze
  condition: succeeded()
  jobs:
  - deployment: DeployApp
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'Azure for Students'
              appName: 'BoardGameApp'
              package: $(Pipeline.Workspace)/drop/*.jar

          - task: OWASP.ZAP.Scanner@1
            inputs:
              scanType: 'baseline'
              targetUrl: 'https://boardgameapp-ayghd3hyfcbkbafd.centralindia-01.azurewebsites.net'
              threshold: '50'
              aggressiveScan: false
